### ISSUE TITLE
GitHub actions README and pkgdown error

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/landscapemetrics#219]
There are some issues with the README and following the homepage. My guess is that Tibble must be installed in the GitHub actions because it seems to be that all "additional" infos that tibble print on the console are broken.

**Comment by mhesselbarth** [comment]
This should be fixed. Problem was the `crayon` package. 

```
- name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
          crayon.enabled: 'FALSE'
```
